COLOR_BACKGROUND = 35, 39, 46
COLOR_POINT_SELECTED = 255, 0, 0
COLOR_POINT_NORMAL = 200, 200, 200
COLOR_LINE_NORMAL = 96, 96, 96, 32

WIDTH, HEIGHT = 640, 640
SIZE = WIDTH, HEIGHT

SYSTEM_WIDTH, SYSTEM_HEIGHT = 16, 16
SYSTEM_SIZE = SYSTEM_WIDTH, SYSTEM_HEIGHT

ROOT_POINT_POSITION = 0, 0

POINT_RADIUS_NORMAL = 2
POINT_RADIUS_SELECTED = 4

WINDOW_ICON_RELATIVE_PATH = "assets/icon.png"
WINDOW_TITLE = "Linked Vectors"

# Pre-computed values
GAP_WIDTH, GAP_HEIGHT = WIDTH / SYSTEM_WIDTH, HEIGHT / SYSTEM_HEIGHT
GAP_SIZE = GAP_WIDTH, GAP_HEIGHT
