COLOR_BACKGROUND = 35, 39, 46
COLOR_POINT_SELECTED = 255, 0, 0
COLOR_POINT_NORMAL = 200, 200, 200
COLOR_LINE_NORMAL = 96, 96, 96, 32

WIDTH, HEIGHT = 640, 640
SIZE = WIDTH, HEIGHT

SYSTEM_WIDTH, SYSTEM_HEIGHT = 32, 32
SYSTEM_SIZE = SYSTEM_WIDTH, SYSTEM_HEIGHT

ROOT_POINT_POSITION = 1, 2

POINT_RADIUS_NORMAL = 1
POINT_RADIUS_SELECTED = 2

# Pre-computed values
GAP_WIDTH, GAP_HEIGHT = WIDTH / SYSTEM_WIDTH, HEIGHT / SYSTEM_HEIGHT
GAP_SIZE = GAP_WIDTH, GAP_HEIGHT
